#ifndef STATUS_AREA_MODULE
#define STATUS_AREA_MODULE

#include "colorpicker.h"
#include "picker_helpers.cpp"

class StatusArea {
protected:
    int length;  /* base length of the string it outputs */
public:
    int get_length(){ return length; }  /* read access to length */
    void set_length(int len){ length = len; } /* write access to length */
};

class Item: public StatusArea{
private:
    int pos=0; /* position in the item pack's skeleton where the item is to be inserted */
    bool shrinkable = true; /* can it generate a string of length other than its base one */
    controllable_properties prop; /* property the status value of which this item generates */
    std::string contents = "aaaaaaaaaaaaaaa"; /* string to store the generated value */

public:
    Item(){} /* empty constructor: needed by vector */
    ~Item(){} /* empty destructor: needed by vector */

    /* copy constructor: needed by vector */
    Item(const Item& that){
        pos = that.pos;
        shrinkable = that.shrinkable;
        prop = that.prop;
        contents = that.contents;
        set_length(((StatusArea)that).get_length());
    }

    /** regular constructor of Item
     * @param position position in the item pack's skeleton where the item is to be inserted
     * @param char_count desired length of the string value generated by the Item
     * @param controller what property to use for generating the value
     * @param placeholder dummy string to initialise
     * @param allow_shrink true by default; 
     * can it generate a string of length other than the provided
     */
    Item(int position, int char_count, controllable_properties controller, std::string placeholder,
            bool allow_shrink=true) {
        pos = position;
        length = char_count;
        shrinkable = allow_shrink;
        contents = placeholder;
        prop = controller;
    }

    int get_pos(){ return pos; } /* read access to the expected position in the pack's skeleton */
    bool is_shrinkable(){ return shrinkable; } /* check if the item has flexible length */
    controllable_properties get_controlled_property(){ return prop; } /* get the flag specifying the generated value's source */
    std::string get_content(){ return contents; } /* get the currently stored string value */

    /* write access to the stored string */
    void set_content(std::string new_content){
        contents = new_content;
    }

    /* generates (and updates) the string value of the item */
    std::string generate_buffer(){
        std::string res="";
        switch (prop) 
        {
        case CC_F_RED: {
            float value=CURRENT_COLOR->red;
            if (value == stof(contents)) {
                niffie("no change");
                break;
            }
            res=std::to_string(Math::round(value,0.001));
            break;
        }
        case CC_F_GREEN: {
            float value=CURRENT_COLOR->green;
            if (value == stof(contents)) {
                niffie("no change");
                break;
            }
            res=std::to_string(Math::round(value,0.001));
            break;
        }
        case CC_F_BLUE: {
            float value=CURRENT_COLOR->blue;
            if (value == stof(contents)) {
                niffie("no change");
                break;
            }
            res=std::to_string(Math::round(value,0.001));
            break;
        }
        case CC_I_RED: {
            int value=std::round(CURRENT_COLOR->red * 255);
            if (value == stoi(contents)) {
                niffie("no change");
                break;
            }
            res=std::to_string(value);
            break;
        }
        case CC_I_GREEN: {
            int value=std::round(CURRENT_COLOR->green * 255);
            if (value == stoi(contents)) {
                niffie("no change");
                break;
            }
            res=std::to_string(value);
            break;
        }
        case CC_I_BLUE: {
            int value=std::round(CURRENT_COLOR->blue * 255);
            if (value == stoi(contents)) {
                niffie("no change");
                break;
            }
            res=std::to_string(value);
            break;
        }
        case CC_ALPHA: {
            float value=CURRENT_COLOR->alpha;
            if (value == stof(contents)) {
                niffie("no change");
                break;
            }
            res=std::to_string(Math::round(value,0.001));
            break;
        }
        case CC_HEX3: {
            int value=std::round(CURRENT_COLOR->red * 255);
            value=256 * value + std::round(CURRENT_COLOR->green * 255);
            value=256 * value + std::round(CURRENT_COLOR->blue * 255);
            if (value == stoi(contents, 0, 16)) {
                niffie("no change");
                break;
            }
            ColorSpaces::RGB8 col={.b=(value%256)};
            value/=256;
            col.g=value%256;
            value/=256;
            col.r=value;
            res=Converter::hex(&col).substr(1, 6);
            break;
        }
        case CC_HUE: {
            ColorSpaces::RGB rgb=_gdk_rgba_to_rgb(CURRENT_COLOR);
            ColorSpaces::HSV temp=Converter::rgb_to_hsv(&rgb);
            float value=temp.h;
            if (value == stof(contents)) {
                niffie("no change");
                break;
            }
            res=std::to_string(Math::round(value,0.001));
            break;
        }
        case CC_HSL_SATURATION: {
            ColorSpaces::RGB rgb=_gdk_rgba_to_rgb(CURRENT_COLOR);
            ColorSpaces::HSL temp=Converter::rgb_to_hsl(&rgb);
            float value=temp.s;
            if (value == stof(contents)) {
                niffie("no change");
                break;
            }
            res=std::to_string(Math::round(value,0.001));
            break;
        }
        case CC_LIGHTNESS: {
            ColorSpaces::RGB rgb=_gdk_rgba_to_rgb(CURRENT_COLOR);
            ColorSpaces::HSL temp=Converter::rgb_to_hsl(&rgb);
            float value=temp.l;
            if (value == stof(contents)) {
                niffie("no change");
                break;
            }
            res=std::to_string(Math::round(value,0.001));
            break;
        }
        case CC_HSV_SATURATION: {
            ColorSpaces::RGB rgb=_gdk_rgba_to_rgb(CURRENT_COLOR);
            ColorSpaces::HSV temp=Converter::rgb_to_hsv(&rgb);
            float value=temp.s;
            if (value == stof(contents)) {
                niffie("no change");
                break;
            }
            res=std::to_string(Math::round(value,0.001));
            break;
        }
        case CC_VALUE: {
            ColorSpaces::RGB rgb=_gdk_rgba_to_rgb(CURRENT_COLOR);
            ColorSpaces::HSV temp=Converter::rgb_to_hsv(&rgb);
            float value=temp.v;
            if (value == stof(contents)) {
                niffie("no change");
                break;
            }
            res=std::to_string(Math::round(value,0.001));
            break;
        }
        default:
            break;
        }

        if(!shrinkable and res.size()<length){
            for(int i=res.size(); i<length;i++){
                res+=' ';
            }
        } else if(res.size() > length){
            res = res.substr(0,length);
        }
        this->set_content(res);
        return res;
    }
};

class ItemPack: public StatusArea{
private: 
    int pos=0; /* position in the status bar's skeleton where the pack is to be inserted */
    std::string container; /* skeleton of the pack, combined with the items when the pack's string is generated */
    bool shrinkable = false; /* whether the generated string can vary in length */
    std::vector<Item> children = std::vector<Item>(0); /* vector of the pack's items */
public:
    ItemPack(){} /* empty constructor: needed by vector */
    ~ItemPack(){} /* empty destructor: needed by vector */

    /* copy constructor: needed by vector */
    ItemPack(const ItemPack& pack){ 
        pos = pack.pos;
        shrinkable = pack.shrinkable;
        children = pack.children;
        container = pack.container;
        set_length(((StatusArea)pack).get_length());
    }

    /** regular constructor of ItemPack 
     * @param start_pos position in the bar's skeleton where the pack is to be inserted
     * @param total_length desired length of the generated string (including items)
     * 
    */
    ItemPack(int start_pos, int total_length, std::string placeholder, bool allow_shrink = false){
        niffie("ipack");
        pos = start_pos;
        length = total_length;
        children = std::vector<Item>(0);
        container = placeholder;
        shrinkable = allow_shrink;
    }
    
    int get_pos(){ return pos; }
    bool is_shrinkable(){ return shrinkable; }
    std::vector<Item> get_children(){ return children; }
    std::string get_container(){ return container; }
    Item get_nth_child(int n){ return children[n]; }

    void set_nth_child(int n, Item child){
        niffie("start setting nth child");
        if(n>=children.size() or n==-1){
            n = children.size();
            niffie("work...");
            children.push_back(child);
            niffie("work...");
        }
        else{
            children[n] = child;
        }
        niffie("end setting nth child");
    }

    std::string generate_buffer(){
        std::string res="";
        std::string partial="";
        int prev = 0;
        for(int i=0;i<children.size();i++){
            partial = container.substr(prev, get_nth_child(i).get_pos() - prev) + get_nth_child(i).generate_buffer();
            res+=partial;
            prev = get_nth_child(i).get_pos();
        }
        res += container.substr(prev, container.size() - prev);
        for(int i = res.size(); i<get_length(); i++){
            res+=' ';
        }
        return res;
    }
};


class StatusBar: public StatusArea{
private:
    GtkWidget* bar;
    GtkWidget* frame;
    std::string skeleton;
    std::vector<ItemPack> contents = std::vector<ItemPack>(0);
public:
    static StatusBar* StatusBar_new(int len, std::string base_string){
        StatusBar* sbar = new StatusBar;
        sbar->frame = gtk_frame_new(NULL);
        sbar->bar = gtk_label_new("test1    ^o^");
        gtk_frame_set_child(GTK_FRAME(sbar->frame), sbar->bar);
        sbar->length = len;
        niffie("uhhh");
        sbar->skeleton = base_string;
        sbar->contents = std::vector<ItemPack>(0);
        niffie("nope");
        gtk_widget_add_css_class(sbar->bar, "mono");
        gtk_label_set_selectable(GTK_LABEL(sbar->bar), true);
        return sbar;
    }

    GtkWidget* get_bar(){ return bar; }
    GtkWidget* get_frame(){ return frame; }
    std::vector<ItemPack> get_contents(){ return contents; }
    ItemPack get_nth_child(int n){ return contents[n]; }
    std::string get_skeleton(){ return skeleton; }

    void set_nth_child(int n, ItemPack child){
        if(n>=contents.size() or n==-1){
            n = contents.size();
            contents.resize(n+1);
            contents[n] = child;
        }
        else{
            contents[n] = child;
        }
    }

    static void update(StatusBar* sbar, gpointer* data = NULL){
        string res="";
        string partial = "";
        int prev = 0;
        for(int i=0; i < sbar->contents.size(); i++){
            partial = sbar->skeleton.substr(prev, sbar->get_nth_child(i).get_pos() - prev) + sbar->get_nth_child(i).generate_buffer();
            res+=partial;
        }
        res += sbar->skeleton.substr(prev, sbar->skeleton.size() - prev);
        for(int i=res.size(); i< sbar->get_length(); i++){
            res+=" ";
        }
        gtk_label_set_text(GTK_LABEL(sbar->bar), res.c_str());
    }
};


#endif
